rework if-elif-else logic

diff --git a/workflow-templates/dotnet-service-deploy-pipeline.yml b/workflow-templates/dotnet-service-deploy-pipeline.yml
--- a/workflow-templates/dotnet-service-deploy-pipeline.yml
+++ b/workflow-templates/dotnet-service-deploy-pipeline.yml
@@ -329,8 +329,6 @@ jobs:
             qa_envs_route="${{ secrets.QA_API_URL }}/environments"
             env_name=${{ env.namespace }}
 
-
-
             put_response=$(curl -X PUT \
               -so "${RESPONSE_FILE}" \
               -w "%{http_code}" $qa_envs_route \
@@ -431,16 +429,16 @@ jobs:
                }" \
           || true )
 
-          if [ "${put_response}" != "200" ]; then
-            echo "Cannot create deployment"
-            echo "${put_response}"
-            cat "${REPONSE_FILE}" && exit 1
-          elif [ "${put_response}" != "409" ]; then
+          if [ "${put_response}" == "200" ]; then
+            echo "Deployment creation OK"
+            exit 0
+          elif [ "${put_response}" == "409" ]; then
             echo "Deployment already exists"
             exit 0
           else
-            echo "Deployment creation OK"
-            exit 0
+            echo "Cannot create deployment"
+            echo "${put_response}"
+            cat "${REPONSE_FILE}" && exit 1
           fi
 
       - name: Parse Jira Keys from All Commits
