dev-381/workflow-templates/pipeline without docker in docker

diff --git a/workflow-templates/sravni-pipeline-publish-to-stage-backoffices.yml b/workflow-templates/sravni-pipeline-publish-to-stage-backoffices.yml
--- a/workflow-templates/sravni-pipeline-publish-to-stage-backoffices.yml
+++ b/workflow-templates/sravni-pipeline-publish-to-stage-backoffices.yml
@@ -135,6 +135,26 @@ jobs:
       backoffice_name: ${{ needs.prepublish.outputs.backoffice_name }}
 
     steps:
+      - name: Install werf CLI
+        uses: werf/actions/install@v1.2
+
+      - name: Install Helm
+        uses: azure/setup-helm@v1
+
+      - name: Install Yandex cli
+        run:  |
+          wget -P tmp/ https://storage.yandexcloud.net/yandexcloud-yc/release/0.85.0/linux/amd64/yc
+          chmod +x tmp/yc
+          mv tmp/yc /usr/local/bin/yc
+          echo ${{ secrets.YANDEX_KEY }} | base64 --decode > tmp/key.json
+          yc config profile create github
+          yc config set service-account-key tmp/key.json
+          yc managed-kubernetes \
+            cluster get-credentials \
+            --cloud-id ${{ secrets.YANDEX_CLOUD_ID }} \
+            --folder-id ${{ secrets.YANDEX_FOLDER_ID }} \
+            yc-stage-k8s --external
+
       #Шаг получения имени неймспейса из имени ветки и его проверка на валидность
       - name: Get namespace name
         id: get_namespace
@@ -161,6 +181,24 @@ jobs:
       - name: Checkout source
         uses: actions/checkout@v2
 
+      - name: Checkout qaenv helpers
+        uses: actions/checkout@v2
+        with:
+          repository: sravni/qa-environment-helpers
+          path: qaenv
+          token: ${{ secrets.GH_TOKEN }}
+          ref: DEV-103
+
+      - name: Checkout helm repo
+        uses: actions/checkout@v2
+        with:
+          repository: sravni/helm-charts
+          path: charts
+          token: ${{ secrets.GH_TOKEN }}
+          ref: 'v0.4.10'
+
+
+
       #Шаг проверки наличия уже созданного неймспейса
       - name: Check if namespace already exists
         run: |
@@ -182,83 +220,55 @@ jobs:
       #Шаг создания неймспейса в qa-dashboard, необходимых ресурсов и ключей identity
       - name: Create namespace
         if: ${{ env.namespace_exists == 0 }}
-        uses: addnab/docker-run-action@v3
-        with:
-          username: ${{ secrets.DOCKER_LOGIN }}
-          password: ${{ secrets.DOCKER_PASS }}
-          registry: ${{ secrets.CONTAINER_REGISTRY }}
-          image: ${{ secrets.CONTAINER_REGISTRY }}/qa-environment-helpers:${{ secrets.QA_ENVIRONMENT_HELPERS_TAG }}
-          options: -w=/charts/qa-environment-helpers
-          run: |
-            echo ${{ secrets.YANDEX_KEY }} | base64 --decode > /key.json
-            yc config profile create github
-            yc config set service-account-key /key.json
-            yc managed-kubernetes \
-              cluster get-credentials \
-              --cloud-id ${{ secrets.YANDEX_CLOUD_ID }} \
-              --folder-id ${{ secrets.YANDEX_FOLDER_ID }} \
-              yc-stage-k8s --external
-            RESPONSE_FILE=/tmp/${{ env.build_number }}.txt
-            qa_envs_route="${{ secrets.QA_API_URL }}/environments"
-            env_name=${{ env.namespace }}
-            put_response=$(curl -X PUT \
-              -so "${RESPONSE_FILE}" \
-              -w "%{http_code}" $qa_envs_route \
-              -H "accept: application/json" \
-              -H "Content-Type: application/json" \
-              --cookie "${{ secrets.YA_AUTH_COOKIE_NAME_VALUE }}" \
-              -d "{ \"createdBy\": \"${{ github.actor }}\", \"kind\": \"QA\", \"name\": \"{{ env.namespace }}\", \"team\": \"${{ env.team }}\"}")
-            if [ "${put_response}" != "200" ]; then
-              echo "Cannot create environment {{ env.namespace }}"
-              cat "${RESPONSE_FILE}" && exit 1
-            fi
-            echo "Environment {{ env.namespace }} has been created"
-            export EnvironmentName=${{ env.namespace }}
-            cat k8s-manifests/new-namespace-yandex.yml | envsubst | kubectl apply -f -
-            echo "Manifest has been applied"
-            /bin/bash /charts/qa-environment-helpers/scripts/identity-key/new-identity-key.sh
-            echo "Identity key has been generated"
-            kubectl -n {{ env.namespace }} create secret generic identity-key --from-file identity.pfx
-            echo "Identity key secret has been created"
-            kubectl -n {{ env.namespace }} create secret generic labs-identity-key --from-file identity.pfx
-            echo "Labs identity key secret has been created"
+        run: |
+          RESPONSE_FILE=/tmp/${{ env.build_number }}.txt
+          qa_envs_route="${{ secrets.QA_API_URL }}/environments"
+          env_name=${{ env.namespace }}
+          put_response=$(curl -X PUT \
+            -so "${RESPONSE_FILE}" \
+            -w "%{http_code}" $qa_envs_route \
+            -H "accept: application/json" \
+            -H "Content-Type: application/json" \
+            --cookie "${{ secrets.YA_AUTH_COOKIE_NAME_VALUE }}" \
+            -d "{ \"createdBy\": \"${{ github.actor }}\", \"kind\": \"QA\", \"name\": \"{{ env.namespace }}\", \"team\": \"${{ env.team }}\"}")
+          if [ "${put_response}" != "200" ]; then
+            echo "Cannot create environment {{ env.namespace }}"
+            cat "${RESPONSE_FILE}" && exit 1
+          fi
+          echo "Environment {{ env.namespace }} has been created"
+          export EnvironmentName=${{ env.namespace }}
+          cat qaenv/k8s-manifests/new-namespace-yandex.yml | envsubst | kubectl apply -f -
+          echo "Manifest has been applied"
+          /bin/bash qaenv/scripts/identity-key/new-identity-key.sh
+          echo "Identity key has been generated"
+          kubectl -n {{ env.namespace }} create secret generic identity-key --from-file identity.pfx
+          echo "Identity key secret has been created"
+          kubectl -n {{ env.namespace }} create secret generic labs-identity-key --from-file identity.pfx
+          echo "Labs identity key secret has been created"
 
       #Шаг деплоя в стейдж
       - name: Publish
-        uses: addnab/docker-run-action@v3
-        with:
-          username: ${{ secrets.DOCKER_LOGIN }}
-          password: ${{ secrets.DOCKER_PASS }}
-          registry: ${{ secrets.CONTAINER_REGISTRY }}
-          image: ${{ secrets.CONTAINER_REGISTRY }}/helm-charts:${{ secrets.HELM_CHARTS_TAG }}
-          options: --rm -i -v ${{ github.workspace }}:/app -w=/app
-          run: |
-            echo ${{ secrets.YANDEX_KEY }} | base64 --decode > /key.json
-            yc config profile create github
-            yc config set service-account-key /key.json
-            yc managed-kubernetes \
-              cluster get-credentials \
-              --cloud-id ${{ secrets.YANDEX_CLOUD_ID }} \
-              --folder-id ${{ secrets.YANDEX_FOLDER_ID }} \
-              yc-stage-k8s --external
-            echo "Trying to deploy ${{ env.backoffice_name }}..."
-            werf helm upgrade --install \
-              "${{ env.backoffice_name }}" \
-              --namespace "${{ env.namespace }}" \
-              --timeout 10m \
-              --wait \
-              --set global.image.repository="${{ secrets.CONTAINER_REGISTRY }}/${{ env.backoffice_name }}" \
-              --set global.image.tag="${{ env.build_number }}" \
-              --set global.imagePullSecrets[0]="${{ env.image_pull_secret_acr }}" \
-              --set cronjobs.defaults.resources.enabled=false \
-              --set resources.enabled=false \
-              -f ./"${{ matrix.backoffice }}"/.k8s/ya-stage.yaml \
-              /charts/generic-application/ \
-              2>&1
-            if [ $? != 0 ]; then
-              echo "Publish failed, see logs" && exit 1
-            fi
-            echo "Done"
+        working-directory: ./charts/generic-application/
+        run: |
+          echo "Trying to deploy ${{ env.backoffice_name }}..."
+          helm dependencies update
+          werf helm upgrade --install \
+            "${{ env.backoffice_name }}" \
+            --namespace "${{ env.namespace }}" \
+            --timeout 10m \
+            --wait \
+            --set global.image.repository="${{ secrets.CONTAINER_REGISTRY }}/${{ env.backoffice_name }}" \
+            --set global.image.tag="${{ env.build_number }}" \
+            --set global.imagePullSecrets[0]="${{ env.image_pull_secret_acr }}" \
+            --set cronjobs.defaults.resources.enabled=false \
+            --set resources.enabled=false \
+            -f ../.././"${{ matrix.backoffice }}"/.k8s/ya-stage.yaml \
+            ./ \
+            2>&1
+          if [ $? != 0 ]; then
+            echo "Publish failed, see logs" && exit 1
+          fi
+          echo "Done"
 
       #Шаг отправки информации о деплое в qa-dashboard
       - name: Set info about deployment to qa-environment-service
