DEV-103 add manifest workflow (#8)

diff --git a/workflow-templates/sravni-pipeline-publish-to-stage-manifest.yml b/workflow-templates/sravni-pipeline-publish-to-stage-manifest.yml
--- a/workflow-templates/sravni-pipeline-publish-to-stage-manifest.yml
+++ b/workflow-templates/sravni-pipeline-publish-to-stage-manifest.yml
@@ -1,37 +1,31 @@
-name: Publish-to-Stage-Mono
+name: Publish-to-Stage-Manifest
 
+#Запуск на любой пуш в мастер ветку или на создание/редактирование ПРа
 on:
   push:
     branches:
       - master
+      - yandex
   pull_request:
     branches:
       - master
-    types: [opened, edited]
+      - yandex
 
+#Переменные окружения !!!!!!!!ВАЖНО!!!!!!!!! необходимо прописать свою команду
 env:
   team: <team_name>
   image_pull_secret_acr: sravni-azurecr-io
 
 jobs:
-  get_services:
-    runs-on: ubuntu-latest
-
-    outputs:
-      services: ${{ steps.get-services.outputs.services }}
-
-    steps:
-      - name: Checkout source
-        uses: actions/checkout@v2
-
-      - name: Get services
-        id: get-services
-        run: |
-          services=(*.Service)
-          echo "Services list: ${services}"
-          echo "::set-output name=services::${services}"
-
+#Описание джобы prepublish
   prepublish:
+    #runs-on указывает какой раннер будет использоваться для запуска данной Джобы
+    #ubuntu-latest - офф раннер гитхаба на основе дистрибутива ubuntu
+    #раннеры на основе других дистрибутивов можно найти в следующей доке:
+    #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
+    #                           !!!!!!!!!!!!ВАЖНО!!!!!!!!!!
+    #sravni_ycloud_stage - наш раннер, необходимо указывать при наличии интегротестов
+    #                          !!!!!!!!!!!!!!!!!!!!!!!!!!!!
     runs-on: ubuntu-latest
 
     outputs:
@@ -39,34 +33,40 @@ jobs:
       service_name: ${{ env.service_name }}
       build_number: ${{ env.build_number }}
 
-    strategy:
-      matrix:
-        service: ${{ needs.get_services.outputs.services }}
-
     steps:
+      #checkout - собственно чекаут репозитория
       - name: Checkout source
         uses: actions/checkout@v2
 
+      #Шаги проверки ивента и выставления имени бранчи в зависимости от него
       - name: Get branch name (merge)
         if: github.event_name != 'pull_request'
-        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
+        run: |
+          branch=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
+          if [ $branch == "yandex" ]; then branch="master";fi
+          echo "branch=$branch" >> $GITHUB_ENV
 
       - name: Get branch name (pull request)
         if: github.event_name == 'pull_request'
-        run: echo "branch=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
+        run: |
+          branch=$(echo ${GITHUB_HEAD_REF} | tr / -)
+          if [ $branch == "yandex" ]; then branch="master";fi
+          echo "branch=$branch" >> $GITHUB_ENV
 
+      #Шаг получения необходимых переменных для работы пайплайна
+      #service_name - получается из имени репозитория, например osago-frontend
+      #build_number - тег нашего образа, состоит из sha коммита и постфикса qa для стейдж окружения, для прода постфикс отсутствует
+      #image_name - полное имя образа, к примеру sravni.azurecr.io/osago-frontend:ha751ufq
       - name: Set build vars to GITHUB_ENV
         run: |
-          service_name=${{ matrix.service }}
-          service_name=$(echo "${service_name}" | tr '[:upper:]' '[:lower:]')
-          service_name=${service_name//./-}
-          sha=$(echo ${GITHUB_SHA} | cut -c1-7)
-          build_number=$sha-qa
+          service_name=$(basename `git rev-parse --show-toplevel`)
+          build_number=$(echo ${GITHUB_SHA} | cut -c1-7)
           image_name="${{ secrets.CONTAINER_REGISTRY }}/${service_name}:${build_number}"
           echo "service_name=$service_name" >> $GITHUB_ENV
           echo "build_number=$build_number" >> $GITHUB_ENV
           echo "image_name=$image_name" >> $GITHUB_ENV
 
+      #Шаг логина в наш реджестри в Azure
       - name: Login to ACR
         uses: docker/login-action@v1
         with:
@@ -74,34 +74,34 @@ jobs:
           username: ${{ secrets.DOCKER_LOGIN }}
           password: ${{ secrets.DOCKER_PASS }}
 
-      - name: Set up Docker Buildx
-        id: buildx
-        uses: docker/setup-buildx-action@v1
-
+      #Шаг сборки образа (с пушем)
       - name: Docker build
         id: docker_build
         uses: docker/build-push-action@v2
         with:
           context: .
-          file: ./${{ matrix.service }}/Dockerfile
+          file: Dockerfile
           build-args: |
-            GITHUB_NPM_TOKEN=${{ secrets.GH_TOKEN }}
             build_number=${{ env.build_number }}
+            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
+            GITHUB_USERNAME=${{ secrets.NUGET_USERNAME }}
+            GITHUB_NPM_TOKEN=${{ secrets.GH_TOKEN }}
           push: true
           tags: "${{ env.image_name }}"
 
   publish:
     runs-on: ubuntu-latest
-    needs: [prepublish, get_services]
+    needs: [ prepublish ]
 
-    strategy:
-      matrix:
-        service: ${{ needs.get_services.outputs.services) }}
-
+    #Все шаги будут использовать переменные окружения с предыдущей джобы
     env:
       build_number: ${{ needs.prepublish.outputs.build_number }}
       branch: ${{ needs.prepublish.outputs.branch }}
+      service_name: ${{ needs.prepublish.outputs.service_name }}
 
+    #Шаг получения имени неймспейса
+    #Имя неймспейса образуется из названия ветки, не должно содержать спецсимволов
+    #и должно быть не более 14 символов
     steps:
       - name: Get namespace name
         id: get_namespace
@@ -128,23 +128,25 @@ jobs:
       - name: Checkout source
         uses: actions/checkout@v2
 
+      #Шаг получения проверки существования неймспейса в qa-dashboard
       - name: Check if namespace already exists
         run: |
           RESPONSE_FILE=/tmp/$(uuidgen).txt
           qa_envs_route="${{ secrets.QA_API_URL }}/environments"
-          get_response=$(curl -X GET -so "${RESPONSE_FILE}" -w "%{http_code}" ${qa_envs_route}/{{ env.namespace }} \
+          get_response=$(curl -X GET -so "${RESPONSE_FILE}" -w "%{http_code}" ${qa_envs_route}/${{ env.namespace }} \
           --cookie "${{ secrets.YA_AUTH_COOKIE_NAME_VALUE }}" \
           -H "accept: application/json")
           namespace_exists=0
           if [ $get_response == "200" ]; then
-              echo "Environment {{ env.namespace }} already exists"
-              namespace_exists=1
+           echo "Environment ${{ env.namespace }} already exists"
+           namespace_exists=1
           elif [ $get_response != "404" ]; then
-              echo "Server returned:"
-              cat "${RESPONSE_FILE}" && exit 1
+           echo "Server returned:"
+           cat "${RESPONSE_FILE}" && exit 1
           fi
           echo "namespace_exists=${namespace_exists}" >> $GITHUB_ENV
 
+      #Шаг создания неймспейса и всех необходимых для его работоспособности секретов
       - name: Create namespace
         if: ${{ env.namespace_exists == 0 }}
         uses: addnab/docker-run-action@v3
@@ -165,29 +167,29 @@ jobs:
               yc-stage-k8s --external
             RESPONSE_FILE=/tmp/$(uuidgen).txt
             qa_envs_route="${{ secrets.QA_API_URL }}/environments"
-            env_name=${{ env.namespace }}
             put_response=$(curl -X PUT \
               -so "${RESPONSE_FILE}" \
               -w "%{http_code}" $qa_envs_route \
               -H "accept: application/json" \
               -H "Content-Type: application/json" \
               --cookie "${{ secrets.YA_AUTH_COOKIE_NAME_VALUE }}" \
-              -d "{ \"createdBy\": \"${{ github.actor }}\", \"kind\": \"QA\", \"name\": \"{{ env.namespace }}\", \"team\": \"<team_name>\"}")
+              -d "{ \"createdBy\": \"${{ github.actor }}\", \"kind\": \"QA\", \"name\": \"${{ env.namespace }}\", \"team\": \"${{ env.team }}\"}")
             if [ "${put_response}" != "200" ]; then
-              echo "Cannot create environment {{ env.namespace }}"
+              echo "Cannot create environment ${{ env.namespace }}"
               cat "${RESPONSE_FILE}" && exit 1
             fi
-            echo "Environment {{ env.namespace }} has been created"
+            echo "Environment ${{ env.namespace }} has been created"
             export EnvironmentName=${{ env.namespace }}
             cat k8s-manifests/new-namespace-yandex.yml | envsubst | kubectl apply -f -
             echo "Manifest has been applied"
             /bin/bash /charts/qa-environment-helpers/scripts/identity-key/new-identity-key.sh
             echo "Identity key has been generated"
-            kubectl -n {{ env.namespace }} create secret generic identity-key --from-file identity.pfx
+            kubectl -n ${{ env.namespace }} create secret generic identity-key --from-file identity.pfx
             echo "Identity key secret has been created"
-            kubectl -n {{ env.namespace }} create secret generic labs-identity-key --from-file identity.pfx
+            kubectl -n ${{ env.namespace }} create secret generic labs-identity-key --from-file identity.pfx
             echo "Labs identity key secret has been created"
 
+      #Шаг деплоя приложения в Stage
       - name: Publish
         uses: addnab/docker-run-action@v3
         with:
@@ -206,24 +208,13 @@ jobs:
               --folder-id ${{ secrets.YANDEX_FOLDER_ID }} \
               yc-stage-k8s --external
             echo "Trying to deploy ${{ env.service_name }}..."
-            werf helm upgrade --install \
-              "${{ env.service_name }}" \
-              --namespace "${{ env.namespace }}" \
-              --timeout 10m \
-              --wait \
-              --set global.image.repository="${{ secrets.CONTAINER_REGISTRY }}/${{ env.service_name }}" \
-              --set global.image.tag="${{ env.build_number }}" \
-              --set global.imagePullSecrets[0]="${{ env.image_pull_secret_acr }}" \
-              --set cronjobs.defaults.resources.enabled=false \
-              --set resources.enabled=false \
-              -f ./"${{ matrix.service }}".k8s/ya-stage.yaml \
-              /charts/generic-application/ \
-              2>&1
-            if [ $? != 0 ]; then
-              echo "Publish failed, see logs" && exit 1
-            fi
-            echo "Done"
+            export IMAGE_VERSION=${{ env.build_number }}
+            echo $IMAGE_VERSION
+            export DEPLOY_NAMESPACE=${{ env.namespace }}
+            echo $DEPLOY_NAMESPACE
+            cat /app/k8s/ya-stage.yaml | envsubst | kubectl apply -f -
 
+      #Шаг отправки информации в qa-enviroment-service
       - name: Set info about deployment to qa-environment-service
         if: ${{ success() }}
         run: |
