dev-549/workflow-templates/fix pipelines for php services

diff --git a/workflow-templates/sravni-pipeline-publish-to-prod-php.yml b/workflow-templates/sravni-pipeline-publish-to-prod-php.yml
--- a/workflow-templates/sravni-pipeline-publish-to-prod-php.yml
+++ b/workflow-templates/sravni-pipeline-publish-to-prod-php.yml
@@ -1,5 +1,6 @@
-name: Publish-to-Prod-Multi-Services
+name: Publish-to-Prod-PHP-Multi-Services
 
+#Запуск на проставление тега или выпуск релиза
 on:
   push:
     tags:
@@ -8,11 +9,15 @@ on:
     types:
       - published
 
+#Переменные окружения !!!!!!!!ВАЖНО!!!!!!!!! необходимо прописать свою команду
 env:
   team: <team_name>
   image_pull_secret_acr: sravni-azurecr-io
 
+#Описание Джобов воркфлоу
 jobs:
+  #Описание Джобы get_services и ее шага, в котором происходит составление
+  #матрицы бэкоффисов по маске *.Services и ее сохранения для дальнейшего использования
   get_services:
     runs-on: ubuntu-latest
 
@@ -20,19 +25,27 @@ jobs:
       services: ${{ steps.get-services.outputs.services }}
 
     steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
+      - name: Checkout source
+        uses: actions/checkout@v2
 
       - name: Get services
         id: get-services
         run: |
-          services=(*.Service)
-          echo "Services list: ${services}"
+          services=$(ls -d .k8s/services/*.Service | sed 's|.*/\([^/]*\)$|\1|' | jq -R '[.]' | jq -s -c 'add')
+          echo "services list: ${services}"
           echo "::set-output name=services::${services}"
 
+#Описание джобы prepublish
   prepublish:
+    #runs-on указывает какой раннер будет использоваться для запуска данной Джобы
+    #ubuntu-latest - офф раннер гитхаба на основе дистрибутива ubuntu
+    #раннеры на основе других дистрибутивов можно найти в следующей доке:
+    #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
+    #                           !!!!!!!!!!!!ВАЖНО!!!!!!!!!!
+    #sravni_ycloud_stage - наш раннер, необходимо указывать при наличии интегротестов
+    #                          !!!!!!!!!!!!!!!!!!!!!!!!!!!!
     runs-on: ubuntu-latest
+    needs: [get_services]
 
     outputs:
       branch: ${{ env.branch }}
@@ -41,28 +54,29 @@ jobs:
 
     strategy:
       matrix:
-        service: ${{ needs.get_services.outputs.services }}
+        service: ${{ fromJson(needs.get_services.outputs.services) }}
 
     steps:
+      #checkout - собственно чекаут репозитория
       - name: Checkout source
         uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
 
+      #Шаг получения необходимых переменных для работы пайплайна
+      #service_name - получается из имени репозитория, например osago-frontend
+      #build_number - тег нашего образа, состоит из sha коммита и постфикса qa для стейдж окружения, для прода постфикс отсутствует
+      #image_name - полное имя образа, к примеру sravni.azurecr.io/osago-frontend:ha751ufq
       - name: Set build vars to GITHUB_ENV
         run: |
           service_name=${{ matrix.service }}
           service_name=$(echo "${service_name}" | tr '[:upper:]' '[:lower:]')
           service_name=${service_name//./-}
-          branch=$(echo ${GITHUB_REF#refs/heads/})
-          sha=$(echo ${GITHUB_SHA} | cut -c1-7)
-          build_number=$sha
+          build_number=$(echo ${GITHUB_SHA} | cut -c1-7)
           image_name="${{ secrets.CONTAINER_REGISTRY }}/${service_name}:${build_number}"
-          echo "service_name=$service_name" >> $GITHUB_ENV
           echo "branch=$branch" >> $GITHUB_ENV
           echo "build_number=$build_number" >> $GITHUB_ENV
           echo "image_name=$image_name" >> $GITHUB_ENV
 
+      #Шаг логина в наш реджестри в Azure
       - name: Login to ACR
         uses: docker/login-action@v1
         with:
@@ -70,35 +84,59 @@ jobs:
           username: ${{ secrets.DOCKER_LOGIN }}
           password: ${{ secrets.DOCKER_PASS }}
 
-      - name: Set up Docker Buildx
-        id: buildx
-        uses: docker/setup-buildx-action@v1
-
+      #Шаг сборки образа (с пушем)
       - name: Docker build
         id: docker_build
         uses: docker/build-push-action@v2
         with:
           context: .
-          file: ./${{ matrix.service }}/Dockerfile
+          file: ./docker/services/${{ matrix.service }}/Dockerfile
           build-args: |
-            GITHUB_NPM_TOKEN=${{ secrets.GH_TOKEN }}
             build_number=${{ env.build_number }}
+            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
+            GITHUB_USERNAME=sravni
+            GITHUB_NPM_TOKEN=${{ secrets.GH_TOKEN }}
           push: true
           tags: "${{ env.image_name }}"
 
+#Описание джобы publish
   publish:
     runs-on: ubuntu-latest
     needs: [prepublish, get_services]
 
+    #Все шаги будут примерняться на матрице, полученной в предыдущей джобе
     strategy:
       matrix:
-        service: ${{ needs.get_services.outputs.services) }}
+        service: ${{ fromJson(needs.get_services.outputs.services) }}
 
+    #Все шаги будут использовать переменные окружения с предыдущей джобы
     env:
-      branch: ${{ needs.prepublish.outputs.branch }}
       build_number: ${{ needs.prepublish.outputs.build_number }}
+      branch: ${{ needs.prepublish.outputs.branch }}
+      service_name: ${{ needs.prepublish.outputs.service_name }}
 
     steps:
+
+      - name: Install werf CLI
+        uses: werf/actions/install@v1.2
+
+      - name: Install Helm
+        uses: azure/setup-helm@v1
+
+      - name: Azure Login
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+      - name: Azure CLI script
+        uses: azure/CLI@v1
+        with:
+          azcliversion: 2.30.0
+          inlineScript: |
+            az aks get-credentials --admin \
+              --resource-group sravni \
+              --name az-prod-k8s
+
       - name: Login to ACR
         uses: docker/login-action@v1
         with:
@@ -108,45 +146,50 @@ jobs:
 
       - name: Checkout source
         uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
 
+      - name: Checkout qaenv helpers
+        uses: actions/checkout@v2
+        with:
+          repository: sravni/qa-environment-helpers
+          path: qaenv
+          token: ${{ secrets.GH_TOKEN }}
+          ref: ${{ secrets.QAENV_REF }}
+
+      - name: Checkout helm repo
+        uses: actions/checkout@v2
+        with:
+          repository: sravni/helm-charts
+          path: charts
+          token: ${{ secrets.GH_TOKEN }}
+          ref: '${{ secrets.CHARTS_REF }}'
+
+      #Шаг деплоя в прод Azure
       - name: Publish
-        uses: addnab/docker-run-action@v3
+        working-directory: ./charts/generic-application/
+        run: |
+          service_name=${{ matrix.service }}
+          service_name=$(echo "${service_name}" | tr '[:upper:]' '[:lower:]')
+          service_name=${service_name//./-}
+          echo "Deploying service ${service_name}..."
+          werf helm upgrade --install \
+            "${service_name}" \
+            --namespace sravni \
+            --atomic \
+            --timeout 10m \
+            --set global.image.repository="${{ secrets.CONTAINER_REGISTRY }}/${service_name}" \
+            --set global.image.tag="${{ env.build_number }}" \
+            --set global.imagePullSecrets[0]="${{ env.image_pull_secret_acr }}" \
+            --set azureRedis.uri=${{ secrets.AZURE_REDIS_URI }} \
+            --set linkerd.enabled=false \
+            -f ../../.k8s/services/"${{ matrix.service }}"/azure.yaml \
+            ./ \
+            2>&1
+          if [ $? != 0 ]; then
+            echo "Publish failed, see logs" && exit 1
+          fi
+          echo "Done"
 
-        with:
-          username: ${{ secrets.DOCKER_LOGIN }}
-          password: ${{ secrets.DOCKER_PASS }}
-          registry: ${{ secrets.CONTAINER_REGISTRY }}
-          image: ${{ secrets.CONTAINER_REGISTRY }}/qa-environment-helpers:${{ secrets.QA_ENVIRONMENT_HELPERS_TAG }}
-          options: --rm -i -v ${{ github.workspace }}:/app -w=/app
-          run: |
-            az login --service-principal \
-              --username ${{ secrets.ARM_CLIENT_ID }} \
-              --password ${{ secrets.ARM_CLIENT_SECRET }} \
-              --tenant ${{ secrets.ARM_TENANT_ID }}
-            az aks get-credentials --admin \
-              --resource-group sravni \
-              --name az-prod-k8s
-            echo "Deploying service ${{ env.service_name }}..."
-            werf helm upgrade --install \
-              "${{ env.service_name }}" \
-              --namespace sravni \
-              --atomic \
-              --timeout 10m \
-              --set global.image.repository="${{ secrets.CONTAINER_REGISTRY }}/${{ env.service_name }}" \
-              --set global.image.tag="${{ env.build_number }}" \
-              --set global.imagePullSecrets[0]="${{ env.image_pull_secret_acr }}" \
-              --set azureRedis.uri=${{ secrets.AZURE_REDIS_URI }} \
-              --set linkerd.enabled=false \
-              -f ./"${{ matrix.service }}".k8s/azure.yaml \
-              /charts/generic-application/
-              2>&1
-            if [ $? != 0 ]; then
-              echo "Publish failed, see logs" && exit 1
-            fi
-            echo "Done"
-
+      #Шаги выставления стейда деплоя
       - name: Failed Deployment
         if: ${{ failure() }}
         run: echo "DEPLOY_STATE=failed" >> $GITHUB_ENV
@@ -155,6 +198,7 @@ jobs:
         if: ${{ success() }}
         run: echo "DEPLOY_STATE=successful" >> $GITHUB_ENV
 
+      #Шаги подготовки данных для пуша деплоймента в Jira
       - name: Parse Jira Keys from All Commits
         id: jira_keys
         if: ${{ always() }}
@@ -175,10 +219,11 @@ jobs:
         if: ${{ always() }}
         run: |
           dep_url="${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
-          title="@${{env.committer}} опубликовал(а) релиз \`${{env.service_name}}\`"
+          title="@${{env.committer}} опубликовал(а) релиз \`${{ matrix.service }}\`"
           title+=" версии <${dep_url}|'${{env.build_number}}'> из ветки \`${{env.branch}}\`"
           echo "DEPLOY_NAME=${title}" >> $GITHUB_ENV
 
+      #Шаг пуша деплоймента в Jira
       - name: Push Deployment Info to Jira
         if: steps.jira_keys.outputs.jira-keys != ''
         id: push_deployment_info_to_jira
