DEV-518 remove qa-env image from prod deploy

diff --git a/workflow-templates/sravni-pipeline-publish-to-prod-multi-services.yml b/workflow-templates/sravni-pipeline-publish-to-prod-multi-services.yml
--- a/workflow-templates/sravni-pipeline-publish-to-prod-multi-services.yml
+++ b/workflow-templates/sravni-pipeline-publish-to-prod-multi-services.yml
@@ -67,6 +67,9 @@ jobs:
       #image_name - полное имя образа, к примеру sravni.azurecr.io/osago-frontend:ha751ufq
       - name: Set build vars to GITHUB_ENV
         run: |
+          service_name=${{ matrix.service }}
+          service_name=$(echo "${service_name}" | tr '[:upper:]' '[:lower:]')
+          service_name=${service_name//./-}
           build_number=$(echo ${GITHUB_SHA} | cut -c1-7)
           image_name="${{ secrets.CONTAINER_REGISTRY }}/${service_name}:${build_number}"
           echo "branch=$branch" >> $GITHUB_ENV
@@ -113,6 +116,27 @@ jobs:
       service_name: ${{ needs.prepublish.outputs.service_name }}
 
     steps:
+
+      - name: Install werf CLI
+        uses: werf/actions/install@v1.2
+
+      - name: Install Helm
+        uses: azure/setup-helm@v1
+
+      - name: Azure Login
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+      - name: Azure CLI script
+        uses: azure/CLI@v1
+        with:
+          azcliversion: 2.30.0
+          inlineScript: |
+            az aks get-credentials --admin \
+              --resource-group sravni \
+              --name az-prod-k8s
+
       - name: Login to ACR
         uses: docker/login-action@v1
         with:
@@ -123,44 +147,47 @@ jobs:
       - name: Checkout source
         uses: actions/checkout@v2
 
+      - name: Checkout qaenv helpers
+        uses: actions/checkout@v2
+        with:
+          repository: sravni/qa-environment-helpers
+          path: qaenv
+          token: ${{ secrets.GH_TOKEN }}
+          ref: ${{ secrets.QAENV_REF }}
+
+      - name: Checkout helm repo
+        uses: actions/checkout@v2
+        with:
+          repository: sravni/helm-charts
+          path: charts
+          token: ${{ secrets.GH_TOKEN }}
+          ref: '${{ secrets.CHARTS_REF }}'
+
       #Шаг деплоя в прод Azure
       - name: Publish
-        uses: addnab/docker-run-action@v3
-        with:
-          username: ${{ secrets.DOCKER_LOGIN }}
-          password: ${{ secrets.DOCKER_PASS }}
-          registry: ${{ secrets.CONTAINER_REGISTRY }}
-          image: ${{ secrets.CONTAINER_REGISTRY }}/qa-environment-helpers:${{ secrets.QA_ENVIRONMENT_HELPERS_TAG }}
-          options: --rm -i -v ${{ github.workspace }}:/app -w=/app
-          run: |
-            service_name=${{ matrix.service }}
-            service_name=$(echo "${service_name}" | tr '[:upper:]' '[:lower:]')
-            service_name=${service_name//./-}
-            az login --service-principal \
-              --username ${{ secrets.ARM_CLIENT_ID }} \
-              --password ${{ secrets.ARM_CLIENT_SECRET }} \
-              --tenant ${{ secrets.ARM_TENANT_ID }}
-            az aks get-credentials --admin \
-              --resource-group sravni \
-              --name az-prod-k8s
-            echo "Deploying service ${service_name}..."
-            werf helm upgrade --install \
-              "${service_name}" \
-              --namespace sravni \
-              --atomic \
-              --timeout 10m \
-              --set global.image.repository="${{ secrets.CONTAINER_REGISTRY }}/${service_name}" \
-              --set global.image.tag="${{ env.build_number }}" \
-              --set global.imagePullSecrets[0]="${{ env.image_pull_secret_acr }}" \
-              --set azureRedis.uri=${{ secrets.AZURE_REDIS_URI }} \
-              --set linkerd.enabled=false \
-              -f ./"${{ matrix.service }}"/.k8s/azure.yaml \
-              /charts/generic-application/
-              2>&1
-            if [ $? != 0 ]; then
-              echo "Publish failed, see logs" && exit 1
-            fi
-            echo "Done"
+        working-directory: ./charts/generic-application/
+        run: |
+          service_name=${{ matrix.service }}
+          service_name=$(echo "${service_name}" | tr '[:upper:]' '[:lower:]')
+          service_name=${service_name//./-}
+          echo "Deploying service ${service_name}..."
+          werf helm upgrade --install \
+            "${service_name}" \
+            --namespace sravni \
+            --atomic \
+            --timeout 10m \
+            --set global.image.repository="${{ secrets.CONTAINER_REGISTRY }}/${service_name}" \
+            --set global.image.tag="${{ env.build_number }}" \
+            --set global.imagePullSecrets[0]="${{ env.image_pull_secret_acr }}" \
+            --set azureRedis.uri=${{ secrets.AZURE_REDIS_URI }} \
+            --set linkerd.enabled=false \
+            -f ../.././"${{ matrix.service }}"/.k8s/azure.yaml \
+            ./ \
+            2>&1
+          if [ $? != 0 ]; then
+            echo "Publish failed, see logs" && exit 1
+          fi
+          echo "Done"
 
       #Шаги выставления стейда деплоя
       - name: Failed Deployment
