PE-984: Добавил модульный флоу для публикации в новый yandex prod; добавил возможность задавать в модельных флоу раннера

diff --git a/.github/workflows/sravni-pipeline-publish-to-yandex-prod-multi-projects-module.yml b/.github/workflows/sravni-pipeline-publish-to-yandex-prod-multi-projects-module.yml
--- a/.github/workflows/sravni-pipeline-publish-to-yandex-prod-multi-projects-module.yml
+++ b/.github/workflows/sravni-pipeline-publish-to-yandex-prod-multi-projects-module.yml
@@ -1,16 +1,8 @@
-name: Publish to stage projects base module
+name: Publish to yandex production projects base module
 
 on:
   workflow_call:
     inputs:
-      namespace:
-        description: 'Namespace'
-        required: true 
-        type: string
-      branch_name: 
-        description: "Название ветки"
-        required: true
-        type: string
       projects:
         description: "JSON объект со списком проектов для публикации"
         required: true
@@ -18,7 +10,11 @@ on:
       runner:
         description: "Указывает какой раннер будет использоваться для запуска флоу"
         required: false
-        default: sravni_ycloud_stage
+        default: sravni_prod
+        type: string
+      namespace:
+        description: 'Namespace'
+        required: true
         type: string
     secrets: 
       GH_TOKEN:
@@ -29,20 +25,15 @@ on:
         required: true
       DOCKER_PASS:
         required: true
-      YANDEX_KEY:
-        required: true
-      YANDEX_CLOUD_ID:
-        required: true
-      YANDEX_FOLDER_ID:
-        required: true
-      QA_API_URL:
+      AZURE_CREDENTIALS:
         required: true
       CHARTS_REF:
+        required: true
+      AZURE_REDIS_URI:
         required: true
 
 env:
   NAMESPACE: ${{ inputs.namespace }}
-  BRANCH: ${{ inputs.branch_name }}
   IMAGE_PULL_SECRET_ACR: sravni-azurecr-io
 
 jobs:
@@ -62,19 +53,19 @@ jobs:
         uses: azure/setup-helm@v1
 
       - name: Install Yandex cli
-        run:  |
+        run: |
           wget -P tmp/ https://storage.yandexcloud.net/yandexcloud-yc/release/0.85.0/linux/amd64/yc
           chmod +x tmp/yc
-          mv tmp/yc /usr/local/bin/yc
-          echo ${{ secrets.YANDEX_KEY }} | base64 --decode > tmp/key.json
+          mkdir -p /home/runner/.local/bin
+          mv tmp/yc /home/runner/.local/bin/yc
+          echo ${{ secrets.YANDEX_PROD_KEY }} | base64 --decode > tmp/key.json
           yc config profile create github
           yc config set service-account-key tmp/key.json
           yc managed-kubernetes \
             cluster get-credentials \
-            --cloud-id ${{ secrets.YANDEX_CLOUD_ID }} \
-            --folder-id ${{ secrets.YANDEX_FOLDER_ID }} \
-            yc-stage-k8s --external
-
+            --cloud-id ${{ secrets.YANDEX_PROD_CLOUD_ID }} \
+            --folder-id ${{ secrets.YANDEX_PROD_FOLDER_ID }} \
+            sravni-prod-k8s-workloads --internal
       - name: Login to ACR
         uses: docker/login-action@v1
         with:
@@ -93,6 +84,7 @@ jobs:
           token: ${{ secrets.GH_TOKEN }}
           ref: '${{ secrets.CHARTS_REF }}'
       
+      
       - name: Define chart directory
         run: |
           if echo "${{ matrix.project.project_name }}" | grep -iqF "job" 
@@ -101,14 +93,13 @@ jobs:
           fi
           echo "CHART_DIRECTORY=$chart_directory" >> $GITHUB_ENV
 
-      #Шаг деплоя в стейдж
+      #Шаг деплоя в прод Azure
       - name: Publish
         working-directory: ${{ env.CHART_DIRECTORY }}
         run: |
           project_name="${{ matrix.project.project_name }}"
-          echo "Trying to deploy $project_name..."
-          helm dependencies update
-          werf helm upgrade --install \
+           helm dependencies update
+          werf helm upgrade --install --history-max 2 \
             "$project_name" \
             --namespace "${{ env.NAMESPACE }}" \
             --timeout 10m \
@@ -116,46 +107,10 @@ jobs:
             --set global.image.repository="${{ secrets.CONTAINER_REGISTRY }}/${{ matrix.project.project_name }}" \
             --set global.image.tag="${{ matrix.project.image_version }}" \
             --set global.imagePullSecrets[0]="${{ env.IMAGE_PULL_SECRET_ACR }}" \
-            --set cronjobs.defaults.resources.enabled=false \
-            --set resources.enabled=false \
-            -f ../.././"${{ matrix.project.k8s_yaml_path }}" \
+            -f ../../.k8s/ya-prod.yaml \
             ./ \
             2>&1
           if [ $? != 0 ]; then
-            echo "Publish failed, qsee logs" && exit 1
+            echo "Publish failed, see logs" && exit 1
           fi
           echo "Done"
-
-      #Шаг отправки информации о деплое в qa-dashboard
-      - name: Set info about deployment to qa-environment-service
-        if: ${{ success() }}
-        run: |
-          project_name="${{ matrix.project.project_name }}"
-          echo "DEPLOY_STATE=successful" >> $GITHUB_ENV
-          qa_deps_route="${{ secrets.QA_API_URL }}/deployments"
-          RESPONSE_FILE=/tmp/response.txt
-          put_response=$(curl -X PUT \
-            -so "${RESPONSE_FILE}" \
-            -w "%{http_code}" "${qa_deps_route}" \
-            -H "accept: application/json" \
-            -H "Content-Type: application/json" \
-            --cookie "${{ secrets.YA_AUTH_COOKIE_NAME_VALUE }}" \
-            -d "{ \
-               \"Branch\": \"${{ env.BRANCH }}\", \
-               \"Project\": \"$project_name\", \
-               \"Stand\": \"${{ env.NAMESPACE }}\", \
-               \"TriggeredBy\": \"${{ github.actor }}\", \
-               \"VcsNumber\": \"${{ matrix.project.image_version }}\", \
-               \"buildId\": ${{ github.run_id }} \
-               }")
-          if [ "${put_response}" == "200" ]; then
-            echo "Deployment creation OK"
-            exit 0
-          elif [ "${put_response}" == "409" ]; then
-            echo "Deployment already exists"
-            exit 0
-          else
-            echo "Cannot create deployment"
-            echo "${put_response}"
-            cat "${RESPONSE_FILE}" && exit 1
-          fi
